### PR TITLE
Update LODTable.py

### PR DESCRIPTION
**Pull request by jbzdarkid**
Support for classes and buildings

### CODE REVIEW

**Comment by Moussa** [comment]
This may be a good time for you to learn how to squash up multiple commits into one descriptive commit :3 It's super simple, there's a guide [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). Poke me if you need help.

**Comment by jbzdarkid** [comment]
I'm getting a bit stuck following that guide -- I did a rebase -i HEAD~4 and then squashed, it required me to do a merge (and didn't clean out the commits)
Now when I do it it still requires me to merge, and won't even automerge.

**Comment by Moussa** [comment]
Okay, that's weird. The last commit marked `pick` above the commits you mark `squash` will be the one the commits will be squashed into. I can merge this in and squash the commits myself if you want, but that will change the branch history and might cause a headache for you and your fork.

**Comment by jbzdarkid** [comment]
I usually remove my forks once you've merged, so that'd be fine by me.

**Comment by Moussa** [comment]
All done. Let me know if I messed something up in the merge and squish.

**Pull request merged**
